name: release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  windows-x64-gpu:
    name: vs2019
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
      with:
        path: fisher
    - name: cache-opencv-mobile
      id: cache-opencv-mobile
      uses: actions/cache@v3
      with:
        path: opencv-mobile
        key: opencv-mobile-vs2019-v14
    - name: opencv-mobile
      if: steps.cache-opencv-mobile.outputs.cache-hit != 'true'
      run: |
        Invoke-WebRequest -Uri https://github.com/nihui/opencv-mobile/releases/download/v14/opencv-mobile-4.5.4-windows-vs2019.zip -OutFile opencv-mobile-4.5.4-windows-vs2019.zip
        7z x ./opencv-mobile-4.5.4-windows-vs2019.zip
        mv opencv-mobile-4.5.4-windows-vs2019 opencv-mobile
    - name: cache-ncnn
      id: cache-ncnn
      uses: actions/cache@v3
      with:
        path: ncnn
        key: ncnn-windows-vs2019-20220729
    - name: ncnn
      if: steps.cache-ncnn.outputs.cache-hit != 'true'
      run: |
        Invoke-WebRequest -Uri https://github.com/Tencent/ncnn/releases/download/20220729/ncnn-20220729-windows-vs2019.zip -OutFile ncnn-20220729-windows-vs2019.zip
        7z x ./ncnn-20220729-windows-vs2019.zip
        mv ncnn-20220729-windows-vs2019 ncnn
    - name: vulkansdk
      run: |
        Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/1.3.224.0/windows/VulkanSDK-1.3.224.0-Installer.exe?Human=true -OutFile VulkanSDK.exe
        $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("/S");
        $installer.WaitForExit();
    - name: build
      run: |
        $env:VULKAN_SDK="C:/VulkanSDK/1.3.224.0"
        $env:Path+=";C:/VulkanSDK/1.3.224.0/Bin"
        cd fisher/src
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release
    - name: release
      uses: softprops/action-gh-release@v1
      with:
        files: fisher/src/build/Release/fisher.exe